src/Entity/Shirt.php
<?php

namespace App\Entity;

use App\Repository\ShirtRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ShirtRepository::class)
 */
class Shirt
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Brand;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Color;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Size;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->Brand;
    }

    public function setBrand(string $Brand): self
    {
        $this->Brand = $Brand;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->Size;
    }

    public function setSize(string $Size): self
    {
        $this->Size = $Size;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\RouteCollection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;
use Symfony\Component\Form\Form;
use App\Form\AlbumType;
use App\Entity\Shirt;
use App\Entity\Album;

class ProductsController extends AbstractController
{

    /**
     * @Route("/products", name="app_products")
     */
    public function index(): Response
    {
        return $this->render('products/index.html.twig', [
            'controller_name' => 'ProductsController',
        ]);
    }

      /**
     * @Route("/products/album",name="album_index")
     */
    public function ShowAllAlbum()
    {
     
        $em = $this->getDoctrine()->getManager();

        $albums = $em->getRepository(Album::class)->findAll();
        
        return $this->render('products/product.html.twig', array( 
            'albums' => $albums,
        ));
    }
    /**
     * @Route("/products/album/new",methods={"GET","POST"}, name="album_new")
     */
  public function newAlbum(Request $request)
  {
    $album = new Album();
    $form = $this->createForm('App\Form\AlbumType', $album);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $em = $this->getDoctrine()->getManager();
      $em->persist($album);
      $em->flush();
      return $this->redirectToRoute('album_index');
    }

    return $this->render('products/new.html.twig',array(
        'album' => $album, 'form' => $form->createView()));
  }
 
 
 /**
   * @Route("/products/album/{id}", methods={"GET"}, name="album_show")
   */
  public function showOneAlbum(Album $album)
  {


    return $this->render('products/show.html.twig', array(
      'album' => $album
    ));
  }
 /**
   * @Route("/products/album/delete/{id}", name="album_delete")
   */
  public function deleteAlbum($id)
  {
    $em = $this->getDoctrine()->getManager();
    $album = $em->getRepository('App\Entity\Album')->find($id);
    $em->remove($album);
    $em->flush();
    
    return $this->redirectToRoute('album_index');
  }

  /**
   * @Route("/products/album/edit/{id}", methods={"POST","GET"},name="album_edit")
   */
  public function albumEdit(Request $request, Album $album)
  {
    $editForm = $this->createForm(AlbumType::class, $album);
    $editForm->handleRequest($request);
    if ($editForm->isSubmitted() && $editForm->isValid()) {
      $this->getDoctrine()->getManager()->flush();
      return $this->redirectToRoute('album_edit', array('id' => $album->getId()));
    }
    return $this->render('products/edit_album.html.twig', array(
      'album' => $album,
      'edit_form' => $editForm->createView(),
    ));
  }

     /**
     * @Route("/products/shirt",name="shirt_index")
     */
    public function ShowAllShirt()
    {
        $em = $this->getDoctrine()->getManager();

        $shirts = $em->getRepository(Shirt::class)->findAll();

        return $this->render('products/shirt.html.twig', array(
            'shirts' => $shirts,
        ));
    }
      /**
     * @Route("/products/shirt/new",methods={"GET","POST"}, name="shirt_new")
     */
  public function newShirt(Request $request)
  {
    $shirt = new Shirt();
    $form = $this->createForm('App\Form\ShirtType', $shirt);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $em = $this->getDoctrine()->getManager();
      $em->persist($shirt);
      $em->flush();
      return $this->redirectToRoute('shirt_index');
    }

    return $this->render('products/shirt_new.html.twig',array(
        'shirt' => $shirt, 'form' => $form->createView()));
  }
   
     /**
     * @Route("/products/shirt/{id}",name="shirt_show")
     */
    public function ShowOneShirt(shirt $shirt)
    {
      return $this->render('products/shirt_show.html.twig', array(
        'shirt' => $shirt,
      ));
    }


  /**
   * @Route("/products/shirt/edit/{id}", methods={"POST","GET"},name="shirt_edit")
   */
  public function shirtEdit(Request $request, shirt $shirt)
  {
    $editForm = $this->createForm('App\Form\ShirtType', $shirt);
    $editForm->handleRequest($request);
    if ($editForm->isSubmitted() && $editForm->isValid()) {
      $this->getDoctrine()->getManager()->flush();
      return $this->redirectToRoute('shirt_edit', array('id' => $shirt->getId()));
    }
    return $this->render('products/edit_shirt.html.twig', array(
      'shirt' => $shirt,
      'edit_form' => $editForm->createView(),
    ));
  }

  /**
   * @Route("/products/shirt/delete/{id}", name="shirt_delete")
   */
  public function deleteShirt($id)
  {
    $em = $this->getDoctrine()->getManager();
    $shirt = $em->getRepository('App\Entity\Shirt')->find($id);
    $em->remove($shirt);
    $em->flush();
    
    return $this->redirectToRoute('shirt_index');
  }
  

}

templates/products/edit_album.html.twig
{% extends 'base.html.twig' %}

{% block title %}Musteroid Update{% endblock %}

{% block body %}
  <head>
    <title>Musteroid</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">
    <link rel="icon" href="img/muszoid-removebg-preview1.png">
  
    {% block stylesheets %}

        <style>
          input {
            width: 100%;
            padding: 10px 200px 10px 10px;
            margin: 8px 0px;
            display: inline-block;
            border-radius: 4px;
            border: 1px solid #808080;
            border-left: 6px solid #0B5ED7;
            transition: 0.5s;
          }

          input:focus {
            border: 3px solid #0B5ED7;
          }

          input:hover {
            background-color: rgb(200, 225, 247);
          }

          label {
            border: none;
          }

          input[type=submit] {
            cursor: pointer;
            width: 100%;
            transition: 0.3s;
          }

          .form-group {
            top: 55%;
            left: 50%;
            padding: 30px;
            transform: translate(-50%, -50%);
            position: absolute;
          }
        </style>

    {% endblock %}


  </head>
  <body>
    <div>
       <nav class="navbar navbar-expand-lg navbar-light py-4">
        <div class="container">
          <a href="{{ path('album_index') }}" class="btn btn-outline-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0v-2z"/>
            <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
          </svg>    Back to the list</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav08" aria-controls="nav08" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="nav08">
            <ul class="d-none d-lg-flex navbar-nav mx-auto mt-3 mt-lg-0 mb-3 mb-lg-0 position-absolute top-50 start-50 translate-middle">
              <li class="nav-item me-4"><a class="nav-link" href="../inventory">Home</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../products">Inventory</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../inventory/contact">About Us</a></li>
            </ul>
            <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
              <li class="nav-item me-4"><a class="nav-link" href="../inventory">Home</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../products">Inventory</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../inventory/contact">About Us</a></li>
            </ul>
            <div class="ms-lg-auto">{% if app.user == null %}
              <a class="nav-link" href="/{{app.user ? 'logout' : 'login'}}" @click="isOpen = false"><button class="btn btn-primary me-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>   {{ app.user ? 'Logout' : 'Login' }} </button></a>
              {% else %}
              <a class="nav-link" href="/{{app.user ? 'logout' : 'login'}}" @click="isOpen = false"><button class="btn btn-danger me-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>   {{ app.user ? 'Logout' : 'Login' }} </button></a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      <div class="text-center">
        <h2>Update details of existing product</h2>
      </div>
      <br>
      
      <div class="form-group">
       {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" class="btn btn-primary text-center" />
         {{ form_end(edit_form) }}
      </div>
      

 
      
   
{% endblock %}

templates/products/edit_shirt.html.twig
{% extends 'base.html.twig' %}

{% block title %}Musteroid Update{% endblock %}

{% block body %}
  <head>
    <title>Musteroid</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">
    <link rel="icon" href="img/muszoid-removebg-preview1.png">
  
    {% block stylesheets %}

        <style>
          input {
            width: 100%;
            padding: 10px 200px 10px 10px;
            margin: 8px 0px;
            display: inline-block;
            border-radius: 4px;
            border: 1px solid #808080;
            border-left: 6px solid #0B5ED7;
            transition: 0.5s;
          }

          input:focus {
            border: 3px solid #0B5ED7;
          }

          input:hover {
            background-color: rgb(200, 225, 247);
          }

          label {
            border: none;
          }

          input[type=submit] {
            cursor: pointer;
            width: 100%;
            transition: 0.3s;
          }

          .form-group {
            top: 60%;
            left: 50%;
            padding: 30px;
            transform: translate(-50%, -50%);
            position: absolute;
          }
        </style>

    {% endblock %}


  </head>
  <body>
    <div>
       <nav class="navbar navbar-expand-lg navbar-light py-4">
        <div class="container">
          <a href="{{ path('shirt_index') }}" class="btn btn-outline-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0v-2z"/>
            <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
          </svg>   Back to the list</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav08" aria-controls="nav08" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="nav08">
            <ul class="d-none d-lg-flex navbar-nav mx-auto mt-3 mt-lg-0 mb-3 mb-lg-0 position-absolute top-50 start-50 translate-middle">
              <li class="nav-item me-4"><a class="nav-link" href="../inventory">Home</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../products">Inventory</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../inventory/contact">About Us</a></li>
            </ul>
            <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
              <li class="nav-item me-4"><a class="nav-link" href="../inventory">Home</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../products">Inventory</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../inventory/contact">About Us</a></li>
            </ul>
            <div class="ms-lg-auto">{% if app.user == null %}
              <a class="nav-link" href="/{{app.user ? 'logout' : 'login'}}" @click="isOpen = false"><button class="btn btn-primary me-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>   {{ app.user ? 'Logout' : 'Login' }} </button></a>
              {% else %}
              <a class="nav-link" href="/{{app.user ? 'logout' : 'login'}}" @click="isOpen = false"><button class="btn btn-danger me-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>   {{ app.user ? 'Logout' : 'Login' }} </button></a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      <div class="text-center">
        <h2>Update details of existing product</h2>
      </div>
      <br>
      
      <div class="form-group">
       {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" class="btn btn-primary text-center" />
         {{ form_end(edit_form) }}
      </div>
      

 
      
   
{% endblock %}

templates/products/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Musteroid Display{% endblock %}

{% block body %}
  <head>
    <title>Musteroid</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css">
    <link rel="icon" href="img/muszoid-removebg-preview1.png">

    {% block stylesheets %}

        <style>
          .displayprod {
            top: 40%;
            left: 50%;
            padding: 30px;
            transform: translate(-50%, -50%);
            position: absolute;
          }
        
        </style>

    {% endblock %}
  </head>

  

  <body>
    <div>
       <nav class="navbar navbar-expand-lg navbar-light py-4">
        <div class="container">
           <a href="{{ path('album_index') }}" class="btn btn-outline-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0v-2z"/>
            <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
          </svg>    Back to the list</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav08" aria-controls="nav08" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="nav08">
            <ul class="d-none d-lg-flex navbar-nav mx-auto mt-3 mt-lg-0 mb-3 mb-lg-0 position-absolute top-50 start-50 translate-middle">
              <li class="nav-item me-4"><a class="nav-link" href="../inventory">Home</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../products">Inventory</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../inventory/contact">About Us</a></li>
            </ul>
            <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
              <li class="nav-item me-4"><a class="nav-link" href="../inventory">Home</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../products">Inventory</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="../inventory/contact">About Us</a></li>
            </ul>
            <div class="ms-lg-auto">{% if app.user == null %}
              <a class="nav-link" href="/{{app.user ? 'logout' : 'login'}}" @click="isOpen = false"><button class="btn btn-primary me-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>   {{ app.user ? 'Logout' : 'Login' }} </button></a>
              {% else %}
              <a class="nav-link" href="/{{app.user ? 'logout' : 'login'}}" @click="isOpen = false"><button class="btn btn-danger me-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg>   {{ app.user ? 'Logout' : 'Login' }} </button></a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      <div class="displayprod">
        <div class="card border-primary mb-3" style="max-width: 70rem;">
          <div class="card-header display-6"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-vinyl" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M8 6a2 2 0 1 0 0 4 2 2 0 0 0 0-4zM4 8a4 4 0 1 1 8 0 4 4 0 0 1-8 0z"/>
            <path d="M9 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
          </svg>   Album</div>
          <div class="card-body text-primary">
            <h3 class="card-title d-inline display-4">{{album.name}}       </h5> <small class="text-muted d-inline">by {{album.artist}}</small>
              <br>
            <p class="card-text"><strong>${{album.price}}</strong></p>
            <p class="card-text lead">In stock: {{album.quantity}}</p>
          </div>
        </div>
      </div>

    </body>
      


        
   

 
{% endblock %}